drop table if exists catalog CASCADE;
create table catalog
(
id bigint generated by default as identity,
product_id varchar(255),
product_name varchar(255),
stock integer ,
unit_price integer ,
created_at date default CURRENT_TIMESTAMP(),
primary key (id)
);
